query Centres {
  centres {
    id
    latitude
    longitude
    association {
      nom
    }
    adresse
    jourshoraires {
      lundiMatin
      lundiApresMidi
      mardiMatin
      mardinApresMidi
      mercrediMatin
      mercrediApresMidi
      jeudiMatin
      jeudiApresMidi
      vendrediMatin
      vendrediApresMidi
      samediMatin
      samediApresMidi
      dimancheMatin
      dimancheApresMidi
    }
  }
}
