query Centre($id: ID!) {
  centre(id: $id) {
    id
    association {
      nom
    }
    services {
      id
      nom
      description
      jourshoraires {
        lundiMatin
        lundiApresMidi
        mardiMatin
        mardinApresMidi
        mercrediMatin
        mercrediApresMidi
        jeudiMatin
        jeudiApresMidi
        vendrediMatin
        vendrediApresMidi
        samediMatin
        samediApresMidi
        dimancheMatin
        dimancheApresMidi
      }
    }
    adresse
    jourshoraires {
      lundiMatin
      lundiApresMidi
      mardiMatin
      mardinApresMidi
      mercrediMatin
      mercrediApresMidi
      jeudiMatin
      jeudiApresMidi
      vendrediMatin
      vendrediApresMidi
      samediMatin
      samediApresMidi
      dimancheMatin
      dimancheApresMidi
    }
  }
}
