query Association($id: ID!) {
  association(id: $id) {
    id
    nom
    description
    logo {
      url
    }
    centres{
      id
      lieu{
        libelle
        adresse
        latitude
        longitude
      }
      services{
        id
        nom
        description
        jourshoraires{
          lundiMatin
          lundiApresMidi
          mardiMatin
          mardinApresMidi
          mercrediMatin
          mercrediApresMidi
          jeudiMatin
          jeudiApresMidi
          vendrediMatin
          vendrediApresMidi
          samediMatin
          samediApresMidi
          dimancheMatin
          dimancheApresMidi
          }
      }
      jourshoraires{
        lundiMatin
        lundiApresMidi
        mardiMatin
        mardinApresMidi
        mercrediMatin
        mercrediApresMidi
        jeudiMatin
        jeudiApresMidi
        vendrediMatin
        vendrediApresMidi
        samediMatin
        samediApresMidi
        dimancheMatin
        dimancheApresMidi
        }
   }
  users {
     username
     email
     Nom
     Prenom
     Telephone
     role {
       name
     }
   }
 }
}
