query Associations{
  associations {
    id
    nom
    description
    Adresse
    Email
    logo {
      url
    }
    centres{
      id
      lieu{
        libelle
        adresse
        latitude
        longitude
      }
    }
  }
}
