query Maraudes {
  maraudes {
    id
    lieuDepart
    lieuArrive
    dateDepart
    heureDepart
    lieuRdv
    heureRdv
    enPrevisions
    fini
    user {
      username
      Nom
      Prenom
      association{
        nom
      }
    }
  }
}
