query Maraudes {
  maraudes {
    id
    lieuDepart{
      libelle
      adresse
      latitude
      longitude
    }
    lieuArrive{
      libelle
      adresse
      latitude
      longitude
    }
    lieuRdv{
      libelle
      adresse
      latitude
      longitude
    }
    dateDepart
    heureDepart
    heureRdv
    enPrevisions
    fini
    user {
      username
      Nom
      Prenom
      association{
        nom
      }
    }
  }
}
