query Maraudes {
  maraudes {
    id
    nom
    lieuDepart {
      libelle
      adresse
      latitude
      longitude
    }
    lieuArrive {
      libelle
      adresse
      latitude
      longitude
    }
    lieuRdv {
      libelle
      adresse
      latitude
      longitude
    }
    dateDepart
    heureDepart
    heureRdv
    fini
    user {
      username
      Nom
      Prenom
      association {
        nom
      }
    }
    lignerapports {
      situation
      age,
      nombreHomme,
      nombreFemme,
      nombreEnfant,
      animaux,
      comAnimaux,
      enceinte,
      pbSante,
      secours,
      demandeHebergement,
      logementactuel,
      appel,
      pseudo,
      lieuRencontre
    }
  }
}
