query Services {
  services {
    nom
    description
    centre{
        id
        association{
        nom
        }
        lieu {
        adresse
        longitude
        latitude
        }
    }
  }
}
